= Building Custom Toolchain and Root Filesystem using crosstool-NG and Buildroot
Broadcom Corporation <support@broadcom.com>
v1.0, 2015-04-20: Converted to asciidoc.
:toc:

== crosstool-NG

*crosstool-NG* aims at building toolchains. It allows to generate
toolchains based on uClibc, glibc and eglibc for a wide range of
architectures.

=== Host Requirements

Requires bash 3.1 or newer. You will need the following additional
packages as well:

 * awk
 * bison
 * flex
 * makeinfo
 * automake 1.10 or newer
 * libtool 1.5.26 or newer
 * ncurses

To install the above packages on any ubuntu machine, just do the following:
----
sudo apt-get install gawk bison flex texinfo automake libtool ncurses-dev
----

Ubuntu Version used:

====
[horizontal]
 Distributor ID:: Ubuntu
 Description:: Ubuntu 10.04.1 LTS
 Release:: 10.04
 Codename:: lucid
====

This should be a good version to start with, as it is tested and known
to work.

=== Download and usage

crosstool-NG can be downloaded from http://crosstool-ng.org/#download_and_usage

crosstool-NG version used: crosstool-ng-1.9.0. To download, configure
and build ct-ng:
----
wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.9.0.tar.bz2
tar jxf crosstool-ng-1.9.0.tar.bz2
cd crosstool-ng-1.9.0
./configure --prefix=/work/ct-ng
make
make install
----

Configure and build cross toolchain (example for glibc, mips target)
----
export PATH=.:/work/ct-ng/bin:$PATH
cd /work
mkdir ct-workdir
cd ct-workdir
ct-ng mipsel-unknown-linux-gnu
ct-ng menuconfig
----

Select "Paths and misc options", change "Local tarballs directory"
from "${HOME}/src" to "/work/src".

Change "Prefix directory" from `${HOME}/x-tools/${CT_TARGET}` to
`/work/x-tools/${CT_TARGET}`, and exit to the main menu.

Select "Target options", set "Target Architecture", "Endianness",
change the "Architecture level" to mips32, then set the "Floating
point" and exit to the main menu.

Select "Toolchain options", then set "Tuple's alias" to mipsel-linux
and exit to the main menu.

Select "C-library", then select the C library (glibc/eglibc/uclibc)
and exit to the main menu and save configuration.

Build the toolchain:
----
ct-ng build
----
Toolchain will be installed in /work/x-tools directory.

Project Website/Documentation : http://crosstool-ng.org/

== Buildroot

Buildroot is a set of Makefiles and patches that allow to easily
generate a cross-compilation toolchain, a root filesystem and a Linux
kernel image for your target. Buildroot can be used for either one,
two or all of these options, independently.

=== Obtaining Buildroot

Releases are available at http://buildroot.net/downloads/

Buildroot version used: buildroot-2009.11

=== Using Buildroot

. Download, untar and configure buildroot
+
----
wget http://buildroot.net/downloads/buildroot-2009.11.tar.bz2
tar xjf buildroot-2009.11.tar.bz2
cd buildroot-2009.11
----

. Edit toolchain/external-toolchain/ext-tool.mk and change
`ld-linux.so.*` to `ld.so.*` and `ld-linux.so` to `ld.so`

. Configure buildroot using menuconfig: `make menuconfig`

. Select "Target Architecture",  then select "mipsel/mips"

. Select "Target Architecture Variant", then select "mips 32"

. Select "Toolchain", then select "Toolchain type", then select
"External binary toolchain"

. Select "External toolchain C library", then select "glibc"

. Select "Enable large file (files > 2 GB) support?", "Enable IPv6",
"Enable RPC", "Enable toolchain locale/i18n support?" and "Enable
'program invocation name'"

. Select "Use software floating point by default" for platforms
without Hardware FPU

.  Select "External toolchain path", then enter
/work/x-tools/mipsel-unknown-linux-gnu and exit to the main menu

. Select "Package Selection for the target", select "Show packages
that are also provided by busybox", select "bash", "strace", "screen"
("BusyBox" and "Run BusyBox's own full installation" are enabled by
default.  This should be a good configuration to start with)

. Select "Networking" and then select "bridge-utils" and exit to the
previous menu

. Select "Interpreter languages / Scripting" and then select
"microperl" and then exit to the main menu

. Select "Target filesystem options", then select "cpio the root
filesystem" and "initramfs for initial ramdisk of linux kernel" and
exit to the main menu

. Select "Kernel", then "Kernel type" and select "linux (Advanced
configuration)"

. Select "Linux Kernel Version (Linux <custom> version)", then select
"Linux <custom> version" and leave the "Linux Tarball version" and
"Linux Version" as "2.6.31"

. Remove "patch name" and "patch site"

. Select "kernel binary format", and select vmlinux and exit to the
main menu, exit and save the configuration

. Create "dl" directory, copy Broadcom kernel tarball to the "dl"
directory and then do the following:
+
----
mkdir dl 
cp /path/to/stblinux-2.6.31-2.5.tar.bz2 dl
cp /path/to/uclinux-rootfs-2.6.31-2.5.tar.bz2 dl
cd dl
tar xjf stblinux-2.6.31-2.5.tar.bz2
tar xjf uclinux-rootfs-2.6.31-2.5.tar.bz2
mv  stblinux-2.6.31 linux-2.6.31
tar cjf linux-2.6.31.tar.bz2 linux-2.6.31
----

. Overwrite `target/generic/target_skeleton/etc/inittab` with Broadcom's
`uclinux-rootfs/skel/etc/inittab`
----
cd ..
rm target/generic/target_skeleton/etc/inittab
cp dl/uclinux-rootfs/skel/etc/inittab target/generic/target_skeleton/etc
----

. Edit the linux defconfig with the following settings. Please note
that `bcm7125c0_defconfig` is just used as an example in this document.
+
----
vi dl/linux-2.6.31/arch/mips/configs/bcm7125c0_defconfig

CONFIG_INITRAMFS_SOURCE="/path/to/buildroot/output/images/rootfs.mipsel.cpio"
CONFIG_INITRAMFS_ROOT_UID=0
CONFIG_INITRAMFS_ROOT_GID=0         
CONFIG_INITRAMFS_COMPRESSION_NONE=y
# CONFIG_INITRAMFS_COMPRESSION_GZIP is not set
# CONFIG_INITRAMFS_COMPRESSION_BZIP2 is not set
# CONFIG_INITRAMFS_COMPRESSION_LZMA is not set
CONFIG_IPV6=y
# CONFIG_IPV6_PRIVACY is not set
# CONFIG_IPV6_ROUTER_PREF is not set
# CONFIG_IPV6_OPTIMISTIC_DAD is not set
# CONFIG_INET6_AH is not set
# CONFIG_INET6_ESP is not set	
# CONFIG_INET6_IPCOMP is not set
# CONFIG_IPV6_MIP6 is not set
# CONFIG_INET6_XFRM_TUNNEL is not set
# CONFIG_INET6_TUNNEL is not set
# CONFIG_INET6_XFRM_MODE_TRANSPORT is not set
# CONFIG_INET6_XFRM_MODE_TUNNEL is not set
# CONFIG_INET6_XFRM_MODE_BEET is not set
# CONFIG_INET6_XFRM_MODE_ROUTEOPTIMIZATION is not set
# CONFIG_IPV6_SIT is not set
# CONFIG_IPV6_TUNNEL is not set
# CONFIG_IPV6_MULTIPLE_TABLES is not set
# CONFIG_IPV6_MROUTE is not set
----

==== Building Kernel

. To build the Kernel, go to the root of the buildroot directory and
type:
+
----
make LINUX26_KCONFIG=dl/linux-2.6.31/arch/mips/configs/bcm7125c0_defconfig
----

. The build may fail for bash.  To work around the bash/termcap build
failure, do the following and run 'make' again:
+
 * Modify output/staging/usr/lib/libc.so file as below:
+
----
---GROUP ( /lib/libc.so.6 /usr/lib/libc_nonshared.a  AS_NEEDED ( /lib/ld.so.1 ) 
+++GROUP ( ../../lib/libc.so.6 ../../usr/lib/libc_nonshared.a  AS_NEEDED ( ../../lib/ld.so.1 ) 
----

 * Modify package/bash/bash.mk as below:
+
----
$(BASH_DIR)/.configured: $(BASH_DIR)/.unpacked
# bash_cv_have_mbstate_t=yes
(cd $(BASH_DIR); rm -rf config.cache; \
+++		$(AUTOCONF) && \
$(TARGET_CONFIGURE_OPTS) \
$(TARGET_CONFIGURE_ARGS) \
CCFLAGS_FOR_BUILD="$(HOST_CFLAGS)" \
@@ -92,9 +93,9 @@ endif
# If both bash and busybox are selected, make certain bash wins
# the fight over who gets to own the /bin/sh symlink.
ifeq ($(BR2_PACKAGE_BUSYBOX),y)
---bash: ncurses busybox $(TARGET_DIR)/$(BASH_TARGET_BINARY)
+++bash: ncurses busybox host-autoconf $(TARGET_DIR)/$(BASH_TARGET_BINARY)
else
---bash: ncurses $(TARGET_DIR)/$(BASH_TARGET_BINARY)
+++bash: ncurses host-autoconf $(TARGET_DIR)/$(BASH_TARGET_BINARY)
endif
----

. The resulting linux image (vmlinux) will be in output/images
directory. Here's the boot commandline for booting vmlinux:
+
----
boot -elf tftp_server:vmlinux
----

=== Building Root Filesystem images

To generate rootfs images, nuke output/target/dev/console and do the
following:
----
cp -r output/target/* /path/to/uclinux-rootfs/romfs
cd /path/to/uclinux-rootfs
touch .target
echo buildroot > .target
bin/build_rootfs_images.sh
----

and the rootfs images will be in /path/to/uclinux-rootfs/images

Please read the official Buildroot document at http://buildroot.uclibc.org/buildroot.html

Buildroot Project Website: http://buildroot.net
