= Broadcom Application Note -- STB Linux FAQ
Broadcom Corporation <support@broadcom.com>
v1.0, 2015-04-20: Converted to asciidoc
:toc:
:numbered:

== Which kernel APIs have changed from earlier releases?

Please see:

- http://lwn.net/Articles/2.6-kernel-api/
- http://lwn.net/Articles/183225/

For information on kernels beyond 2.6.31, refer to
http://kernelnewbies.org/LinuxChanges.

== How do I add my application to the rootfs?

The easiest way is to copy it into `uclinux-rootfs/skel` . The
contents of this directory are incorporated directly into all rootfs
and initramfs images.

== How do I run my application on startup?

Create a shell script named `uclinux-rootfs/skel/root/rc.user`. It
will be run at boot time. Alternative: customize
`uclinux-rootfs/skel/etc/init.d/rcS`.

(In many STB projects, the DHCP client and possibly other daemons are
moved out of rcS and placed under the control of the application, so
you may already be modifying this file.)

== I do not see a kernel build target that matches my board/chip. Is there a programmatic way to find out which images to use on my configuration?

Yes, use the board2build.pl script. Here are some examples:

----
cd uclinux-rootfs
perl -w bin/board2build.pl 97466 a0
perl -w bin/board2build.pl 97459 d0
perl -w bin/board2build.pl 97119 a0
----

== How do I cross-compile open source programs downloaded off the web?

Sometimes it can be a little tricky, but here are a few things to try:

 * If the package uses autoconf, you may need to specify the --host parameter:

    ./configure --host=mipsel-linux
+ 
Often, the CC variable will need to be set to mipsel-linux-gcc (or mips-linux-gcc for big-endian):

    make CC=mipsel-linux-gcc
+
If the package depends on another package, you may need to read the
Makefiles and trick it into looking in a nonstandard location for the
dependency:

    # autoconf sometimes takes an optional path for the dependencies:
    cd wget-1.10
    ./configure --with-ssl=/tmp/openssl-0.9.8k

    # sometimes you need to override CFLAGS, CPPFLAGS, LDFLAGS, etc.
    cd gdb-6.8
    make CPPFLAGS="-I/tmp/libtermcap" LDFLAGS="-L/tmp/libtermcap/.libs"
+
In some rare cases it is necessary to edit the "configure" script, the
Makefile, or both, in order to cross-compile the program. This is
becoming less common with the increasing popularity of Linux in the
embedded space, but it still shows up from time to time.

== I have a special bootloader that requires "raw" binary images that can be copied directly into memory, not gzipped ELF files like `vmlinuz-*`. How do I create this raw image?

Broadcom provides a utility which converts the ELF kernel images into
raw binary (or optionally, srec) images. Sample usage:
----
cd uclinux-rootfs
make images-7425b0
perl -w bin/elf2bin.pl images/vmlinuz-7425b0 /tftpboot/vmlinux.bin
----

== How do I boot a raw binary image from CFE?

Load it at 0x80001000, and jump to entry point 0x80001400:
----
CFE> ifconfig -auto eth0
CFE> load -raw HOST:vmlinux.bin -addr=80001000 -max=16777216
CFE> go 0x80001400
----

== Can I mount an NTFS or exFAT partition from the STB?

The 2.6.31+ kernel releases include ntfs-3g in the rootfs, for full
read/write NTFS support. To enable ntfs-3g in the rootfs build:
----
cd uclinux-rootfs
# start with default 7425b0 LE settings
make defaults-7425b0
# enable NTFS in the vendor configuration
perl -w bin/config.pl vendor CONFIG_USER_NTFS_3G=y
# fix up dependencies
make oldconfig
# build kernel/rootfs/flash images
make images
----

To mount an NTFS partition on the STB, use the "ntfs-3g" command instead of "mount":
----
ntfs-3g /dev/sda1 /mnt/hd
----
The "umount" command works as normal on NTFS partitions.

The old read-only, in-kernel NTFS implementation is not supported.

exFAT is not supported.

http://www.tuxera.com/[Tuxera] sells commercially supported,
high-performance kernel drivers for NTFS and exFAT.

== What other build settings do users frequently inquire about?

Here is a table showing some common modifications:

[cols="1,3l",options="header"]
|===============================================================
| Package | Commands

| iperf   |
perl -w bin/config.pl vendor CONFIG_USER_IPERF=y

| tcpdump |
perl -w bin/config.pl vendor CONFIG_USER_TCPDUMP_TCPDUMP=y

| ethtool |
perl -w bin/config.pl vendor CONFIG_USER_ETHTOOL=y

| bonnie++ |
perl -w bin/config.pl vendor CONFIG_USER_BONNIEXX_BONNIEXX=y

| GNU wget with SSL |
perl -w bin/config.pl busybox CONFIG_WGET=n
perl -w bin/config.pl vendor CONFIG_USER_WGET=y
perl -w bin/config.pl vendor CONFIG_USER_WGET_WITH_SSL=y

| hdparm (full version) |
perl -w bin/config.pl busybox CONFIG_HDPARM=n
perl -w bin/config.pl vendor CONFIG_USER_HDPARM_HDPARM=y

| syslogd (full version) |
perl -w bin/config.pl busybox CONFIG_SYSLOGD=n
perl -w bin/config.pl vendor CONFIG_USER_INETUTILS=y
perl -w bin/config.pl vendor CONFIG_USER_INETUTILS_SYSLOGD=y

| dropbear sshd |
perl -w bin/config.pl busybox CONFIG_PASSWD=y
perl -w bin/config.pl vendor CONFIG_USER_SSH_SSHD=y
perl -w bin/config.pl vendor CONFIG_USER_SSH_SSHKEYGEN=y

| Native GDB on target *(GPLv3)* |
perl -w bin/config.pl vendor CONFIG_USER_GDB_GDB=y

| ldconfig |
perl -w bin/config.pl vendor CONFIG_LIB_UCLIBC_LDCONFIG=y

| Disable gdbserver *(GPLv3)* |
perl -w bin/config.pl vendor CONFIG_USER_GDBSERVER_GDBSERVER=n

| Disable WLAN drivers |
perl -w bin/config.pl vendor CONFIG_USER_NONFREE_WLAN=n

| Disable MoCA drivers |
perl -w bin/config.pl vendor CONFIG_USER_NONFREE_MOCA=n

|===============================================================

The procedure is similar to what is shown in the NTFS FAQ entry above:
----
cd uclinux-rootfs
# start with default 7425b0 LE settings
make defaults-7425b0
# change the configuration
perl -w bin/config.pl first_setting
perl -w bin/config.pl next_setting
...
# fix up dependencies
make oldconfig
# build kernel/rootfs/flash images
make images
----

== Broadcom releases a new reference kernel almost every month.  How do I keep up?

Most projects quickly reach a point where a particular version of the
reference kernel is stable and functional enough to meet the
requirements. Usually the project developers will then "freeze" their
kernel tree instead of tracking each new Broadcom release.

After freezing the tree, it is a good idea to review the release notes
for each subsequent Broadcom reference kernel to look for any bugs
that may apply to your platform. Most Broadcom kernel enhancements are
to support new products and features, so the majority of changes can
usually be skipped.

== Can Broadcom maintain a custom kernel, root filesystem, or toolchain for my project?

Sorry, we cannot. However, numerous third parties are able to provide
this service: MontaVista, TimeSys, Red Hat, Mentor Embedded, and
others.

== What is this GPLv3 warning I see every time I boot the target?

The default rootfs contains gdbserver, which is covered under the
GPLv3 license. GPLv3 programs must *NEVER* be installed on a production
set-top box (i.e. any device on which security is enabled). The terms
of the GPLv3 license may force you to divulge your private signing
keys to end users so that they can modify the operating software on
their set-top boxes.

The "-small" builds, intended to be used as a basis for a production
system, do not include gdb, gdbserver, or any other GPLv3 components.

== Why do I get "bad page state" kernel warnings during O_DIRECT I/O?

An example of this warning:
----
BUG: Bad page state in process brutus  pfn:08c63
page:81119c60 flags:00000010 count:0 mapcount:1 mapping:(null) index:0
Call Trace:
[<80017e54>] dump_stack+0x8/0x34
[<8008565c>] bad_page+0xcc/0x184
[<8008cff8>] put_page+0xb4/0x200
[<800f4414>] dio_bio_complete+0xb8/0x130
[<800f5c88>] __blockdev_direct_IO+0xdd8/0x113c
[<8012e354>] ext4_direct_IO+0xc0/0x2e4
[<80081b3c>] generic_file_aio_read+0x3e4/0x99c
[<800b9418>] do_sync_read+0xd8/0x15c
[<800b9d28>] vfs_read+0xbc/0x154
[<800ba45c>] sys_read+0x50/0xbc
[<8000339c>] stack_done+0x20/0x3c
----

This message usually means that the application is performing direct
I/O on a memory range for which the kernel does not maintain page
tables. This can happen if the "mem=" argument is passed to a 2.6.31+
kernel to limit the amount of memory that Linux knows about, but the
application attempts to perform direct I/O on memory outside of this
range.

In general, "mem=" should not be specified at all on 2.6.31+. To
reserve a particular region of memory for A/V buffers, use the "bmem="
parameter, documented in link:quickstart.html[quickstart]. The default
setting reserves all lower memory above 64MB (up to the 256MB mark)
for Nexus/PI, and most users will not need to override it.

== Can CFE write Linux rootfs images to the flash?

In general, no. For NAND, this would require moving GPLed BBT
management code into the non-GPL CFE, which is not permitted under the
terms of the license. For anything based on UBI (UBIFS on NOR/NAND, or
SQUASHFS on NAND), the same concern applies to the GPLed UBI code.

In addition, CFE was never designed to understand Linux filesystems,
and there is little reason to duplicate this functionality in CFE
since it is already present in the kernel.

== How do I enable iptables/netfilter?

Use the "-netfilter" build variant to enable the appropriate
kernel/rootfs configuration options. Example for 7425b0:
----
cd uclinux-rootfs
make images-7425b0-netfilter
----

== How do I enable the login prompt on the serial port?

First, edit `uclinux-rootfs/skel/etc/inittab` to uncomment the getty
line, and comment out the login line:
----
# Put a shell on the serial port
ttyS0::respawn:/sbin/getty -L 115200 ttyS0 vt102
# ttyS0::respawn:/bin/login -f root
----

Optionally, you may set a root password by pasting the encrypted
password into `uclinux-rootfs/skel/etc/passwd`. First, run `htpasswd`
on a Linux PC to generate the encrypted password (in this case the
cleartext password is `test`):
----
$ htpasswd -bc /dev/stdout root test
Adding password for user root
root:vtDa1cB7mCB3Q
----

Then add the encrypted string into `uclinux-rootfs/skel/etc/passwd`,
between the two colons:
----
root:vtDa1cB7mCB3Q:0:0:root:/root:/bin/sh
----

== How do I move the serial console to ttyS1 (UARTB) or ttyS2 (UARTC)?

There are two steps:

. Edit =uclinux-rootfs/skel/etc/inittab= and change the port on which
the bash console will be started:

    ttyS1::respawn:/bin/login -f root

. Update the kernel configuration to reflect the new port (0, 1, or 2):

    cd uclinux-rootfs
    # start with default 7425b0 LE settings
    make defaults-7425b0
    # switch default to ttyS1
    perl -w bin/config.pl linux CONFIG_BRCM_CONSOLE_DEVICE=1
    # fix up dependencies
    make oldconfig
    # build kernel/rootfs/flash images
    make images

Step 2 may be skipped if you override the console setting on the kernel command line:

    BOLT> boot HOST:vmlinuz-initrd-7425b0 "console=ttyS1,115200"

== How do I disable all UART / console / printk activity?

CFE normally sets up  the pinmux to connect the TX and  RX pins to the
internal  UARTA  core.  This  setting  is done  in  the  CFE  function
`rockford/bsp/bcm*/no-os/src/sde/uart.s:init_serial()`.  To disable the
serial console, use setting `0x0` to set up each pin as a GPIO instead
of a UART.  The default setting is `0x00000001` on most chips:

    li v0, (0x00000001<<BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_015_SHIFT)

Broadcom does *not* recommend disabling the Linux serial drivers as
this will break multiple dependencies.

If you only need to limit the kernel boot messages, an alternative is
to disable `CONFIG_EARLY_PRINTK` and then boot the kernel with the
`quiet` command line option.

== How do I change the MTD partition map?

See the link:nand.html[NAND FAQ].

== What were the scheduler changes between 2.6.18 and 2.6.31?

Linux 2.6.23 introduced the
http://people.redhat.com/mingo/cfs-scheduler/sched-design-CFS.txt[Completely Fair Scheduler].
CFS replaced the old "O(1) scheduler" used in 2.6.18. We are not aware
of any way to run the O(1) scheduler on 2.6.31.

By default, CFS
http://lkml.indiana.edu/hypermail/linux/kernel/0808.2/0078.html[does change]
the way realtime `SCHED_RR` and `SCHED_FIFO` threads are
handled. Starting from 2.6.31-2.1, Broadcom's
`uclinux-rootfs/skel/etc/init.d/rcS` startup script attempts to restore
the old behavior by modifying one of the sysctl parameters:
----
# Don't let SCHED_FIFO / SCHED_RR realtime threads get preempted
echo -1 > /proc/sys/kernel/sched_rt_runtime_us
----
Any other scheduling differences seen when migrating from 2.6.18 to
2.6.31 lie completely outside the scope of Broadcom's kernel changes,
and should be taken up directly with Ingo Molnar (CFS author) and/or
LKML.

The scheduler is unchanged between 2.6.31 and 2.6.37+.

== Can the system automount USB drives when they are connected to the STB?

Yes - edit `uclinux-rootfs/skel/sbin/stbhotplug` and set
`AUTOMOUNT=1`. The default mount point will be `/mnt/usb`.

== How do I rename a network interface?

Build the `nameif` applet from busybox:
----
cd uclinux-rootfs
make defaults-7425b0
perl -w bin/config.pl busybox CONFIG_NAMEIF=y
make oldconfig
make images
----
Then on the target side, to rename `eth1` to `moca0`:
----
ifdown eth1
macaddr=`cat /sys/class/net/eth1/address`
nameif moca0 $macaddr
ifup moca0
----

== Why aren't the BogoMIPS values the same on each CPU?

BogoMIPS in general is only a rough estimate of the number of loops
the CPU can execute in a given time period. In the case of BMIPS5000,
there is often a larger disparity because the two virtual CPUs
(threads) on each processor core share the same pipelines. When the
CPU0 BogoMIPS calculation is performed, only CPU0 is running, but when
the CPU1 BogoMIPS calculation is performed, both CPU0 and CPU1 are
sharing the same execution resources, so the CPU1 value will be lower.

This is harmless.

== Why am I getting a "DRAM0 wraparound" panic?

DRAM wraparound occurs when the CFE memory configuration does not
match the hardware that is physically present on the board, so CFE is
telling Linux that more DRAM exists than what is addressable using the
controller's current settings. This is a fatal error and it needs to
be fixed before Linux will function correctly.

If you see this message, try upgrading to the latest CFE release. If
that doesn't work, file a bug against CFE.

== What are the "delta" patch files?

The delta files show the difference between the upstream (kernel.org)
Linux tree and the Broadcom Linux tree. For instance, `linux/Makefile`
indicates that the baseline for the Broadcom 3.3-2.2 release was
kernel.org release 3.3.8:
----
VERSION = 3
PATCHLEVEL = 3
SUBLEVEL = 8
#EXTRAVERSION =
EXTRAVERSION = -2.2
----
* `delta-3.3-2.2-brcm-new.patch.bz2` contains the *new* files that Broadcom added to the tree.
* `delta-3.3-2.2-brcm-changed.patch.bz2` contains the *changes* that
  Broadcom made to the files from upstream.
* `stblinux-3.3-2.2.tar.bz2` already contains all of these modifications.

It is *not* necessary to apply the patch files to the bundled stblinux
tree; they are only provided for reference. They may be useful if it
is necessary to port the Broadcom changes to a different kernel.org
release, or integrate the Broadcom changes with buildroot.
