= STB Linux Toolchain
Broadcom Corporation <support@broadcom.com>
v1.1, 2015-06-30: Note required vagrant version.
:toc:
:source-highlighter: coderay

== stbgcc 4.8 toolchains

The stbgcc-4.8 toolchains, optional for 3.8-2.0+, bring in eglibc to
replace uClibc with a faster, more complete C library
implementation.  It uses the gcc 4.8 release series, which provides
much improved printing of errors and warnings to help with debugging,
experimental support for C++11, and several optimizer improvements,
including polyhedral optimization for nested loops and a new general
optimization option `-Og` for fast compilation and debugging.
Starting with stbgcc-4.8-0.5,
https://code.google.com/p/address-sanitizer/[AddressSanitizer]
is supported for ARM targets.

Primary contents of the stbgcc-4.8-1.2 release:

- Linaro GCC 4.8-2014.11
- Linaro eglibc 2.24-2013.10
- Linaro binutils 2.24-2014.11
- Linaro GDB 7.7.1-2014.06-1
- Linux 3.8 kernel headers

The stbgcc toolchains are composed of these files (where x, y, and
z are replaced with the corresponding version numbers):

- `stbgcc-4.8-x.y.src.rpm` - Source code and build script,
in RPM format 
- `stbgcc-4.8-x.y.tar.bz2` - Binary tarball for non-RPM
systems 
- `stbgcc-4.8-x.y.i386.rpm` - Binary RPM 

=== Building stbgcc 4.8

To simplify reproducing a working toolchain build environment,
Broadcom provides a prebuilt image that can be automatically set up
using Vagrant.  This is the best way to start building toolchains
right away.

Alternatively, the old method of configuring your own machine as a
build system.

==== Building the toolchain using Vagrant

NOTE: Vagrant version 1.5.0 or newer is required.

In order to build the toolchain using Vagrant, please install
https://www.virtualbox.org/[Virtualbox] and
install http://www.vagrantup.com/[Vagrant], then
download link:toolchain_files/vagrant.zip[vagrant.zip] and
unpack the archive.  Inside the resulting directory, there should be a
file named Vagrantfile.  The directory containing the Vagrantfile will
be considered the "top-level vagrant directory" here. Copy the source
RPM (For release x.y, this is stbgcc-4.8-x.y.src.rpm) into the
top-level vagrant directory and run
`vagrant up`; this will download, configure, and start the
virtual machine.

Once the VM is configured, launch the VM shell by running
`vagrant ssh`, then start the build:

----
$ vagrant ssh
Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic-pae i686)

 * Documentation:  https://help.ubuntu.com/
Welcome to your Vagrant-built virtual machine.
Last login: Tue Mar 11 23:41:35 2014 from 10.0.2.2
vagrant@precise32:~$ bash build-toolchain.sh --first-run
----

The option `--first-run` tells the script to unpack the
source RPM.

Once the build is complete, log out of the VM.  The
directory `out` will contain the toolchain RPMs and
tarball.

----
$ cd vagrant/
$ ls
out  bootstrap.sh  build-toolchain.sh  Vagrantfile
$ ls out
stbgcc-4.8-1.0.i386.rpm  stbgcc-4.8-1.0.src.rpm  stbgcc-4.8-1.0.tar.bz2
----

The RPM build directory in the VM is located
in `/home/vagrant/rpmbuilds`.  To customize your toolchain,
edit the contents of `SPECS/stbgcc-4.8.spec` and
the `SOURCES` folder as necessary.

When done with the VM, run "vagrant destroy" to clean up your VM
(this will not delete the output directory containing the built
toolchains).  See the http://docs.vagrantup.com/[Vagrant docs] for
more info on using Vagrant.

==== Manually configuring a build machine

Broadcom builds the stbgcc-4.8 toolchain on an Ubuntu 12.04 LTS IA32
system.  In order to enable compatibility across multiple
distributions, the toolchains are built using headers and library
stubs from the
http://www.linuxfoundation.org/collaborate/workgroups/lsb[Linux Standard Base]
(LSB) SDK.  The targeted specification is 
http://refspecs.linuxfoundation.org/LSB_3.0.0/[LSB 3.0] and
compatibility is verified by using the
http://ispras.linuxbase.org/index.php/About_Linux_Application_Checker[LSB Linux App Checker].
The toolchain has been determined to be compatible with Red Hat
Enterprise 4 and above, as well as all other tested distributions released
since RHEL 4, but testing has so far been limited to RHEL 4, RHEL 5, RHEL 6,
Ubuntu 12.04 LTS, Ubuntu 13.04, and Ubuntu 14.04 LTS.

Download and install the LSB SDK from the
http://www.linuxfoundation.org/collaborate/workgroups/lsb[Linux Standard Base website].

The distributed binaries of stbgcc-4.8 use the hard float ABI.
The toolchain can also be built for soft float (or alternative softfp
on ARM), but most recent Broadcom STB products have a hardware FPU and would
not benefit from a soft float toolchain (see
<<floating_point,Floating Point Support>>).

In order to build the toolchain on Ubuntu 12.04, the following
packages must be installed in addition to the LSB SDK:

- build-essential
- gawk
- lsb
- pkg-config
- rpm
- texinfo
- ncurses-dev (required for gdb)

These can be installed using

----
sudo apt-get install build-essential gawk lsb ncurses-dev pkg-config texinfo
----

In order to build the toolchain on RHEL 6, the "Development Tools"
group must be installed.  In order to build gdb, ncurses-devel is also
required.  These can be installed by running the following:

----
yum groupinstall 'Development Tools' && yum install ncurses-devel
----

Broadcom supports installing the sources and building the toolchain as
a non-root user on Ubuntu 12.04 LTS and RHEL 5 and 6 (CentOS 5 and 6
should also work).

The following instructions assume you want to
use `$HOME/rpmbuilds` as your RPM build directory:

----
# first-time setup
MY_RPM_BUILD_DIR="$HOME/rpmbuilds"
echo "%_topdir $MY_RPM_BUILD_DIR" >> $HOME/.rpmmacros

# install the source RPM to your rpm build dir
rpm -i stbgcc-4.8-x.y.src.rpm

# Use one of the following, depending on distribution.
# If you want to speed things up, try adding the option '--with parallel'.
cd $MY_RPM_BUILD_DIR
# Debian/Ubuntu
rpmbuild -ba --nodeps --define '_tmppath /tmp' SPECS/stbgcc-4.8.spec 2>&1 | tee BUILD/buildlog
# RHEL/CentOS
rpmbuild -ba --define '_tmppath /tmp' SPECS/stbgcc-4.8.spec 2>&1 | tee BUILD/buildlog

# Go do something else while you wait for the build to finish (takes
# an hour using '--with-parallel' on a fast machine when building for
# both mips and arm)

# It's done!  Install the toolchain to /opt/toolchains:
rpm -ivh RPMS/stbgcc-4.8-x.y.i386.rpm
----

To learn more, including how to create a binary tarball to use
instead that you can place wherever you want, please see the
<<rpm_crash_course,RPM-building crash course>>.

Finally, here's an example of how you would build the kernel and
rootfs, using the 3.14-1.1 release with the stbgcc-4.8-1.0 toolchain,
for BCM7445:
----
tar -jxf /tmp/uclinux-rootfs-3.14-1.1.tar.bz2
tar -jxf /tmp/stblinux-3.14-1.1.tar.bz2
cd uclinux-rootfs
export PATH=/opt/toolchains/stbgcc-4.8-1.0/bin:$PATH
make images-7445d0
----

[[rpm_crash_course]]
=== RPM-building crash course

The directories in the RPM build directory (system directory
is `/usr/src/redhat`, we assume yours is `$HOME/rpmbuilds`) serve
the following purposes:

- `RPMS` - Binary RPMs generated by the build, filed by machine 
architecture.

- `SRPMS` - Source RPMs generated by the build.  These are
architecture-independent files which contain the spec file, source tarballs,
and source patches.

- `SOURCES` - Source tarballs and patches.  This directory is
populated by "rpm -i" when installing the SRPM.

- `SPECS` - Spec files (essentially a build script for the RPM).

- `BUILD` - Used for temporary storage during the build process.

As part of the cleanup stage, the toolchain RPM build process will
delete the buildlog and the temporary installation directory.  As long
as you're not running as root, it can't touch the actual install
directory, but consider yourself warned that if you build as root and
set the buildroot to something strange you could delete files from
your actual install destination.
The buildlog (in gzipped form) gets incorporated into the binary RPM.

The following procedure can be used to convert the binary RPM into a
`tar.bz2` file (run _this_ as root):

----
cd "$MY_RPM_BUILD_DIR/BUILD"
rpm2cpio &lt; ../RPMS/i386/stbgcc-4.8-x.y.i386.rpm | cpio -id
tar -C opt/toolchains -jcf stbgcc-4.8-x.y.tar.bz2 stbgcc-4.8-x.y
rm -rf opt
----

Broadcom maintains a changelog at the end of the RPM spec file, to keep
track of updates to each toolchain release.  This gets built into each RPM
output file.  To view the changelog, use RPM:

----
rpm -qp --changelog stbgcc-4.8-x.y.i386.rpm | less
----

=== Installation

STB Linux toolchains are generally untarred into `/opt/toolchains:`

----
cd /opt/toolchains
tar -jxf /tmp/stbgcc-4.8-x.y.tar.bz2
----

Broadcom toolchains are built in such a way that they can be installed in
arbitrary directories (including user home directories), so root access is not
required. However, the final path should not have any spaces in it.

On 64-bit hosts you may need to install the IA32 compatibility libraries if
you download the binary release.
They are typically already present on 64-bit RHEL/CentOS installations, but
optional on some other distributions.  To install the IA32 libraries and
other build dependencies on Ubuntu:

----
# Ubuntu 12.04 and earlier
sudo apt-get install ia32-libs build-essential
# newer Ubuntu
sudo apt-get install build-essential lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6
----

If the IA32 libraries are missing, toolchain components may return a cryptic
error:

----
bash: /opt/toolchains/stbgcc-4.8-1.0/bin/arm-linux-gnueabihf-gcc: No such file or directory
----

[[floating_point]]
== Floating point support

Hard float toolchains generate floating point instructions on MIPS and ARM.

=== ARM floating point

----
    8438:       ed1b6b03        vldr    d6, [fp, #-12]
    843c:       ed1b7b05        vldr    d7, [fp, #-20]  ; 0xffffffec
    8440:       ee367b07        vadd.f64        d7, d6, d7
    8444:       e30804d4        movw    r0, #34004      ; 0x84d4
    8448:       e3400000        movt    r0, #0
    844c:       ec532b17        vmov    r2, r3, d7
----

On ARM, there are a few different floating-point options: hard-float
("hard"), soft-float ("soft"), and "softfp".  The distinction is not
obvious, so here's a quick summary:

- "soft" uses the soft floating-point ABI.  The compiler will not
  generate floating point instructions, and floating-point operations
  will be emulated by the compiler.
- "softfp" uses the soft floating-point ABI.  The compiler will pass
  floating-point arguments in integer registers, and the compiler will
  generate emulated or real FPU instructions depending on chosen FPU.
  This has a considerable performance impact compared to "hard" but
  will provided better performance than "soft" on machines with an
  FPU.
- "hard" uses full hardware floating point, and the resulting code
  will only run if the hardware supports the instructions generated.

For a more detailed comparison, see
https://wiki.debian.org/ArmHardFloatPort/VfpComparison#Details_on_GCC_floating-point_options

On ARM, the hard and soft ABIs are not compatible---you cannot use
objects targeting one ABI with the other.  stbgcc-4.8 releases are all
hard-float.

=== MIPS floating point

----
  400534:       f7cc0008        sdc1    $f12,8(s8)
  400538:       d7c20008        ldc1    $f2,8(s8)
  40053c:       3c020040        lui     v0,0x40
  400540:       d4400630        ldc1    $f0,1584(v0)
  400544:       46201000        add.d   $f0,$f2,$f0
  400548:       4620000d        trunc.w.d       $f0,$f0
  40054c:       44020000        mfc1    v0,$f0
----

MIPS CPUs which receive hard-float instructions and cannot execute
them will trap into the kernel, and the instructions will be emulated
by the `arch/mips/math-emu` code.

Soft float toolchains generate library calls into libgcc, not FPU
instructions:

----
  400628:       8fc40020        lw      a0,32(s8)
  40062c:       8fc50024        lw      a1,36(s8)
  400630:       8c4611d0        lw      a2,4560(v0)
  400634:       8c4711d4        lw      a3,4564(v0)
  400638:       0c100140        jal     400500 &lt;__adddf3&gt;
  40063c:       00000000        nop
  400640:       8fdc0010        lw      gp,16(s8)
  400644:       00402021        move    a0,v0
  400648:       00602821        move    a1,v1
  40064c:       0c1002f2        jal     400bc8 &lt;__fixdfsi&gt;
  400650:       00000000        nop
----

----
    84c4:       e59f5044        ldr     r5, [pc, #68]   ; 8510 &lt;main+0x78&gt;
    84c8:       e24b1014        sub     r1, fp, #20
    84cc:       e8910003        ldm     r1, {r0, r1}
    84d0:       e24b301c        sub     r3, fp, #28
    84d4:       e893000c        ldm     r3, {r2, r3}
    84d8:       eb000011        bl      8524 &lt;__adddf3&gt;
    84dc:       e1a03000        mov     r3, r0
    84e0:       e1a04001        mov     r4, r1
    84e4:       e1a00005        mov     r0, r5
    84e8:       e1a02003        mov     r2, r3
    84ec:       e1a03004        mov     r3, r4
----

Soft float provides a modest performance boost on non-FPU processors,
but performs very poorly on chips with an FPU.  It is offered as an option
for users who wish to build a custom toolchain, but the default toolchain
on all platforms uses hard float.

To enable soft float in your toolchain build, specify `--with sf`:

----
rpmbuild -ba stbgcc-4.8.spec --with sf 2>&1 | tee buildlog
----

The entire rootfs (all libraries, utilities, and applications) must be
built for either hard float or soft float.  An application built for soft
float will not run correctly if the system libraries were built for hard
float. This is because the ABI and calling conventions are affected by the
use or disuse of the floating point registers (on MIPS, `$f0`-`$f31`).


== uClibc support

Prior to stbgcc-4.8, the standard Broadcom toolchains (prior to stbgcc-4.8)
only supported uClibc (NPTL branch).  A few customer projects may still require
this version of uClibc or the old linuxthreads-based uClibc.  Alternatively,
some may require a different version of glibc than the one provided with
stbgcc-4.8.
In order to help satisfy these requirements,
Broadcom provides a separate link:buildroot.html[application note] with step-by-step
instructions on how to put together a custom toolchain and rootfs for
the STB platform, using crosstools-ng and buildroot.
